import {
  ShoppingBag,
  Coffee,
  Utensils,
  Wine,
  Shirt,
  Smartphone,
  Book,
  Home,
  Apple,
  Gift,
  Brush,
  Camera,
  Music,
  Car,
  PawPrint,
  Dumbbell,
  Flower2,
  Baby,
  Gamepad2,
  Sofa,
  Briefcase,
  Leaf,
  Plane,
  Watch,
  Gem,
  Film,
  Laptop,
  Cloud,
  Cpu,
  Heart,
  Grid,
  List,
  Rows3,
  Grid3X3,
  Package,
  Star,
  Crown,
  Rocket,
} from "lucide-react";
export const iconsList = [
  { id: 0, icon: <Smartphone />, label: "Default" },
  { id: 1, icon: <ShoppingBag />, label: "Shopping" },
  { id: 2, icon: <Coffee />, label: "Coffee" },
  { id: 3, icon: <Utensils />, label: "Meals" },
  { id: 4, icon: <Wine />, label: "Drinks" },
  { id: 5, icon: <Shirt />, label: "Clothing" },
  { id: 6, icon: <Smartphone />, label: "Electronics" },
  { id: 7, icon: <Book />, label: "Books" },
  { id: 8, icon: <Home />, label: "Home" },
  { id: 9, icon: <Apple />, label: "Fruits" },
  { id: 10, icon: <Gift />, label: "Gifts" },
  { id: 11, icon: <Brush />, label: "Art" },
  { id: 12, icon: <Camera />, label: "Photography" },
  { id: 13, icon: <Music />, label: "Music" },
  { id: 14, icon: <Car />, label: "Cars" },
  { id: 15, icon: <PawPrint />, label: "Pets" },
  { id: 16, icon: <Dumbbell />, label: "Fitness" },
  { id: 17, icon: <Flower2 />, label: "Beauty" },
  { id: 18, icon: <Baby />, label: "Baby" },
  { id: 19, icon: <Gamepad2 />, label: "Games" },
  { id: 20, icon: <Sofa />, label: "Furniture" },
  { id: 21, icon: <Briefcase />, label: "Business" },
  { id: 22, icon: <Leaf />, label: "Organic" },
  { id: 23, icon: <Plane />, label: "Travel" },
  { id: 24, icon: <Watch />, label: "Accessories" },
  { id: 25, icon: <Gem />, label: "Jewelry" },
  { id: 26, icon: <Film />, label: "Media" },
  { id: 27, icon: <Laptop />, label: "Tech" },
  { id: 28, icon: <Cloud />, label: "Cloud" },
  { id: 29, icon: <Cpu />, label: "Hardware" },
  { id: 30, icon: <Heart />, label: "Health" },
];

export const pageTypes = (className = "w-4 h-4") => [
  {
    id: "Product",
    icon: <Grid className={className} />,
    lists: ["grid", "list"],
  },
  {
    id: "Menu",
    icon: <List className={className} />,
    lists: ["grid", "list", "menu"],
  },
  { id: "Slideview", icon: <Rows3 className={className} />, lists: ["grid"] },
];

export const pageListStyles = [
  {
    id: "grid",
    label: "Grid",
    preview: <Grid3X3 className="w-6 h-6" />,
  },
  {
    id: "list",
    label: "List",
    preview: <List className="w-6 h-6" />,
  },
  {
    id: "menu",
    label: "Menu",
    preview: <Rows3 className="w-6 h-6" />,
  },
];

export const plans = [
  {
    id: "starter",
    name: "Starter",
    icon: <Package className="w-7 h-7 text-blue-500" />,
    tagline: "Perfect for small businesses taking their first digital step.",
    limits: {
      stores: 1,
      pages: 2,
      products: 50,
    },
    addons: [
      { label: "Extra Store", price: "$4.99 / store" },
      { label: "Extra Page", price: "$1.99 / page" },
      { label: "Extra 50 Products", price: "$2.99" },
    ],
    price: "$5 / month",
    yearlyPrice: "$115 / year",
    accent: "blue",
  },
  {
    id: "pro",
    name: "Pro",
    icon: <Star className="w-7 h-7 text-purple-500" />,
    tagline: "Designed for growing brands and multi-category businesses.",
    limits: {
      stores: 3,
      pages: 10,
      products: 300,
    },
    addons: [
      { label: "Extra Store", price: "$3.99 / store" },
      { label: "Extra Page", price: "$1.49 / page" },
      { label: "Extra 100 Products", price: "$3.99" },
    ],
    price: "$12 / month",
    yearlyPrice: "$115 / year",
    mostPopular: true,
    accent: "purple",
  },
  {
    id: "business",
    name: "Business",
    icon: <Crown className="w-7 h-7 text-amber-500" />,
    tagline: "For structured restaurants, boutiques, lounges & enterprises.",
    limits: {
      stores: 10,
      pages: 25,
      products: 1_000,
    },
    addons: [
      { label: "Extra Store", price: "$2.99 / store" },
      { label: "Extra Page", price: "$0.99 / page" },
      { label: "Extra 200 Products", price: "$4.99" },
    ],
    price: "$25 / month",
    yearlyPrice: "$115 / year",
    accent: "amber",
    support: "Premium",
  },
  {
    id: "elite",
    name: "Elite",
    icon: <Rocket className="w-7 h-7 text-cyan-500" />,
    tagline:
      "Unlimited scalability. Built for franchises, chains, and large brands.",
    limits: {
      stores: "Unlimited",
      pages: "Unlimited",
      products: "Unlimited",
    },
    addons: [
      { label: "Priority Support", price: "Included" },
      { label: "Dedicated Success Manager", price: "Included" },
      { label: "Custom Integrations", price: "Request Quote" },
    ],
    price: "$49 / month",
    yearlyPrice: "$115 / year",
    accent: "cyan",
    support: "Premium",
  },
];

export const userRoles = [
  "Marketer",
  "Product Designer",
  "Sales Manager",
  "Freelancer",
];
