import {
  ShoppingBag,
  Coffee,
  Utensils,
  Wine,
  Shirt,
  Smartphone,
  Book,
  Home,
  Apple,
  Gift,
  Brush,
  Camera,
  Music,
  Car,
  PawPrint,
  Dumbbell,
  Flower2,
  Baby,
  Gamepad2,
  Sofa,
  Briefcase,
  Leaf,
  Plane,
  Watch,
  Gem,
  Film,
  Laptop,
  Cloud,
  Cpu,
  Heart,
} from "lucide-react";
export const iconsList = [
  { id: 1, icon: <ShoppingBag />, label: "Shopping" },
  { id: 2, icon: <Coffee />, label: "Coffee" },
  { id: 3, icon: <Utensils />, label: "Meals" },
  { id: 4, icon: <Wine />, label: "Drinks" },
  { id: 5, icon: <Shirt />, label: "Clothing" },
  { id: 6, icon: <Smartphone />, label: "Electronics" },
  { id: 7, icon: <Book />, label: "Books" },
  { id: 8, icon: <Home />, label: "Home" },
  { id: 9, icon: <Apple />, label: "Fruits" },
  { id: 10, icon: <Gift />, label: "Gifts" },
  { id: 11, icon: <Brush />, label: "Art" },
  { id: 12, icon: <Camera />, label: "Photography" },
  { id: 13, icon: <Music />, label: "Music" },
  { id: 14, icon: <Car />, label: "Cars" },
  { id: 15, icon: <PawPrint />, label: "Pets" },
  { id: 16, icon: <Dumbbell />, label: "Fitness" },
  { id: 17, icon: <Flower2 />, label: "Beauty" },
  { id: 18, icon: <Baby />, label: "Baby" },
  { id: 19, icon: <Gamepad2 />, label: "Games" },
  { id: 20, icon: <Sofa />, label: "Furniture" },
  { id: 21, icon: <Briefcase />, label: "Business" },
  { id: 22, icon: <Leaf />, label: "Organic" },
  { id: 23, icon: <Plane />, label: "Travel" },
  { id: 24, icon: <Watch />, label: "Accessories" },
  { id: 25, icon: <Gem />, label: "Jewelry" },
  { id: 26, icon: <Film />, label: "Media" },
  { id: 27, icon: <Laptop />, label: "Tech" },
  { id: 28, icon: <Cloud />, label: "Cloud" },
  { id: 29, icon: <Cpu />, label: "Hardware" },
  { id: 30, icon: <Heart />, label: "Health" },
];
